workspace:
  base: /srv/app
  path: src/github.com/webhippie/dockerhub_exporter

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    environment:
      - GOPATH=/srv/app
    commands:
      - make style
      - make vet
      - make test
      - make build

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/dockerhub-exporter
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/dockerhub-exporter
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  microbadger:
    image: zyclonite/drone-webhook
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]
      status: [ success ]

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
