FROM webhippie/alpine:latest-amd64@sha256:70823ba293ecd24e536d8da0d20854b9afed1d21fd2715ac7bef620af0161fd6 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="DockerHub Exporter" \
  org.opencontainers.image.documentation="https://promhippie.github.io/dockerhub_exporter/" \
  org.opencontainers.image.vendor="Thomas Boerger"

EXPOSE 9505
ENTRYPOINT ["/usr/bin/dockerhub_exporter"]
HEALTHCHECK CMD ["/usr/bin/dockerhub_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/dockerhub_exporter /usr/bin/dockerhub_exporter
