FROM webhippie/alpine:latest-amd64@sha256:281dc79054f62941f0604ea71e5614d690ed61ace8a64f687e04d077b872195a AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="DockerHub Exporter" \
  org.opencontainers.image.documentation="https://promhippie.github.io/dockerhub_exporter/" \
  org.opencontainers.image.vendor="Thomas Boerger"

EXPOSE 9505
ENTRYPOINT ["/usr/bin/dockerhub_exporter"]
HEALTHCHECK CMD ["/usr/bin/dockerhub_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/dockerhub_exporter /usr/bin/dockerhub_exporter
