FROM webhippie/alpine:latest-amd64@sha256:1340ef3e9b4864e5814723b2c81619480f24cd036a5dab0cb6cee2f693493a15 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="DockerHub Exporter" \
  org.opencontainers.image.documentation="https://promhippie.github.io/dockerhub_exporter/" \
  org.opencontainers.image.vendor="Thomas Boerger"

EXPOSE 9505
ENTRYPOINT ["/usr/bin/dockerhub_exporter"]
HEALTHCHECK CMD ["/usr/bin/dockerhub_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/dockerhub_exporter /usr/bin/dockerhub_exporter
