FROM amd64/alpine:3.20@sha256:dabf91b69c191a1a0a1628fd6bdd029c0c4018041c7f052870bb13c5a222ae76 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9505
ENTRYPOINT ["/usr/bin/dockerhub_exporter"]
HEALTHCHECK CMD ["/usr/bin/dockerhub_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/dockerhub_exporter /usr/bin/dockerhub_exporter
