FROM webhippie/alpine:latest-amd64@sha256:fa3a50df053b32de4d244836d9b0c4e2920cb8d70d9614b84f39225ae4d53199 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="DockerHub Exporter" \
  org.opencontainers.image.documentation="https://promhippie.github.io/dockerhub_exporter/" \
  org.opencontainers.image.vendor="Thomas Boerger"

EXPOSE 9505
ENTRYPOINT ["/usr/bin/dockerhub_exporter"]
HEALTHCHECK CMD ["/usr/bin/dockerhub_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/dockerhub_exporter /usr/bin/dockerhub_exporter
