---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: dockerhub-exporter
  labels:
    app.kubernetes.io/name: dockerhub-exporter
    app.kubernetes.io/component: exporter

spec:
  replicas: 1

  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: dockerhub-exporter
      app.kubernetes.io/component: exporter

  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockerhub-exporter
        app.kubernetes.io/component: exporter

    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      containers:
        - name: exporter
          image: dockerhub-exporter
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: dockerhub-exporter
            - secretRef:
                name: dockerhub-exporter

          ports:
            - name: http
              containerPort: 9505
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: http

          readinessProbe:
            httpGet:
              path: /readyz
              port: http

...
